FROM tb3base:latest

# create the autonomy application overlay in Catkin workspace
RUN source /opt/ros/noetic/setup.bash \
  && mkdir -p /overlay_ws/src \
  && cd /overlay_ws \
  && catkin_init_workspace
# COPY ./tb3_autonomy/ /overlay_ws/src/tbs_autonomy/
# COPY ./tb3_worlds/ /overlay_ws/src/tb3_worlds/
RUN source /opt/ros/noetic/setup.bash \
 && cd /overlay_ws \
 && catkin config --extend /turtlebot3_ws/devel \
 && catkin build -j4

# Set up the work directory and entrypoint
WORKDIR /overlay_ws
